spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/sika-dump
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: postgres
    password: wjc52292
  #  autoconfigure:
    # 避免同时存在多个数据库 starter 冲突与容器启动的密码校验失败
#    exclude: org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
  application:
    name: sika-dump